# This is a basic workflow to help you get started with Actions

name: CI
env:
 MY_URL: http://test
 SECRET_URL: ${{ secrets.MYURL }}
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run if they are same
        if:  ${{ env.MY_URL  == env.SECRET_URL }}
        run: echo Both are same MY_URL${{ env.MY_URL }}-SECRETS.MYURL${{ secrets.MYURL }}!        

      # Runs a set of commands using the runners shell
      - name: Run if they are different       
        if: ${{ env.MY_URL  != env.SECRET_URL }}
        run: echo Both are different MY_URL${{ env.MY_URL }}-SECRETS.MYURL${{ secrets.MYURL }}!   
